name: MALCOLM CLARKE
favicon: null
layout_spectrum: 0.48425
typography_spectrum: 0.77956
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2c3538'
    - '#7c8285'
    - '#dfe1e1'
    - '#606769'
  brandStrength: 0.18232529843226075
  lightness: 0.407839335501194
  saturation: 0.4547600371297449
  rhythmicContrast: 0.9009960223920643
purpose: []
